id: PF1F4B0E4
initial_creation_type: ocr
source_metadata:
  volumes:
    66952cc8b8de4f979a67ff02d7ef5667:
      base_file: v093.txt
      image_group_id: I1PD95938
      title: བསླབ་པ་བཅུའི་ཆོ་ག།
      total_pages: 1484
      volume_number: 93
