id: D930EF80E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-01-07T13:50:45+00:00'
last_modified: '2022-05-30T04:11:27.285530+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    698e:
      image_group_id: I1PD95938
      title: བསླབ་པ་བཅུའི་ཆོ་ག།
      total_pages: 1484
      order: 93
      base_file: 698e.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
